### ISSUE TITLE
add support for resource generators

### ISSUE THREAD

**Issue by bishabosha** [bishabosha/scala-builder#1]
example `builder.toml`:
```toml
scalaVersion = "3.2.2"

# webpage is a Scala.js app, using the DOM API
[modules.webpage]
kind = "application"
mainClass = "example.start"
dependsOn = ["core"] # should smartly chose the js module

# webserver bundles the webpage as a static resource to serve to clients
[modules.webserver]
dependsOn = ["core"] # should smartly chose the jvm module
kind = "application"
mainClass = "example.WebServer"
resourceGenerators = [{ module = "webpage", dest = "assets/main.js" }]

[modules.core]
```

Here is the task graph for `scala-builder run webserver`:
```
- core:main:js
- webpage:linked:js
- webserver:resources1, core:main:jvm
- webserver:runner:jvm
```

- `webserver:resources1` is a target that is the result of copying `webpage:linked:js` output to `managed_resources/assets/main.js`
- `webpage:linked:js` is the task that packages `webpage` as a js script. 

misc explanations:
- `core:main:js` - classpath output of core js library
- `core:main:jvm` - classpath output of core jvm library
- `webserver:runner:jvm` - command to run compiled webserver
